In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/Data (1).csv')
print(df)
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values


   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])
print(x)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(x))
scaler = MinMaxScaler()
x[:, 3:] =  np.round(scaler.fit_transform(x[:, 3:]),2)
print(x)

[[1.0 0.0 0.0 0.74 0.69]
 [0.0 0.0 1.0 0.0 0.0]
 [0.0 1.0 0.0 0.13 0.17]
 [0.0 0.0 1.0 0.48 0.37]
 [0.0 1.0 0.0 0.57 0.45]
 [1.0 0.0 0.0 0.35 0.29]
 [0.0 0.0 1.0 0.51 0.11]
 [1.0 0.0 0.0 0.91 0.89]
 [0.0 1.0 0.0 1.0 1.0]
 [1.0 0.0 0.0 0.43 0.54]]
